In [1]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
a<=6

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [3]:
a[a<=6]

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
a=np.array([10,20,30,40,55])
print(a)

[10 20 30 40 55]


In [5]:
mask=(a%2==0)
a[mask]=-1
print(a)

[-1 -1 -1 -1 55]


In [6]:
#Aggregate Functions
a=np.array([10,20,35,40,55])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))


160
32.0
10
55


In [7]:
a=np.array([10,20,35,40,55])
np.all(a<50)

np.False_

In [8]:
np.any(a<=10)


np.True_

In [10]:
a=np.array([10,20,35,40,55])
b=np.where(a%2!=0,-1,1)
print(b)


[ 1  1 -1  1 -1]


In [12]:
#Sorting
a=np.array([50,30,60,80,90,100])
b=np.sort(a)
print(b)

[ 30  50  60  80  90 100]


In [16]:
a=np.array([50,30,60,80,90,100])
a.sort()
b=a.argsort()
print(a)
print(b)

[ 30  50  60  80  90 100]
[0 1 2 3 4 5]


In [18]:
a=np.arange(5)
a=np.ones(5)
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [21]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(2,14).reshape(3,4)
print(a,"\n""\n",b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [22]:
a+b

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [23]:
b-a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(2,14).reshape(4,3)
print(a,"\n""\n",b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [35]:
a*b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [37]:
c=np.dot(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [39]:
c=a@b
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [41]:
c=np.matmul(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [42]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
b=np.arange(1,6)
b

array([1, 2, 3, 4, 5])

In [46]:
c=np.dot(a,b)
c

np.int64(40)