In [1]:
import numpy as np
bulbs = np.random.binomial(1, 0.5, 10)
print("Generated Values:")
print(bulbs)
working = np.sum(bulbs)
print("Number of Working Bulbs:", working)

Generated Values:
[0 1 1 1 0 1 1 0 1 0]
Number of Working Bulbs: 6


In [2]:
import numpy as np
print("Number of Heads in Each Experiment:")
for i in range(5):
    heads = np.random.binomial(5, 0.5)
    print("Experiment", i + 1, ":", heads)

Number of Heads in Each Experiment:
Experiment 1 : 0
Experiment 2 : 3
Experiment 3 : 3
Experiment 4 : 0
Experiment 5 : 2


In [3]:
import numpy as np
attempts = np.random.geometric(0.5, 10)
print("Generated Values:")
print(attempts)
print("Maximum Attempts Required:", np.max(attempts))

Generated Values:
[3 1 1 1 3 2 3 1 1 1]
Maximum Attempts Required: 3


In [4]:
import numpy as np
customers = np.random.poisson(2, 10)
print("Customer Arrivals:")
print(customers)
print("Highest Customers in an Hour:", np.max(customers))

Customer Arrivals:
[4 2 0 0 3 2 1 0 1 2]
Highest Customers in an Hour: 4


In [5]:
import numpy as np
bernoulli = np.random.binomial(1, 0.5, 5)
binomial = np.random.binomial(5, 0.5, 5)
geometric = np.random.geometric(0.5, 5)
poisson = np.random.poisson(2, 5)

print("Bernoulli Distribution:")
print(bernoulli)
print("\nBinomial Distribution:")
print(binomial)
print("\nGeometric Distribution:")
print(geometric)
print("\nPoisson Distribution:")
print(poisson)

Bernoulli Distribution:
[1 1 1 1 0]

Binomial Distribution:
[2 4 0 2 2]

Geometric Distribution:
[7 1 1 1 2]

Poisson Distribution:
[1 1 1 2 1]
